### PR TITLE
Feature: Add admin queries and mutations

### PR DESCRIPTION
**Pull request by siimsams**
#### What does this PR do?

I added configuration for admin queries and queries themselves to authorizer-js. 

#### Which issue(s) does this PR fix?

Currently there is no way of using this library to query admin queries. It is useful to me as I use js in the backend and i'd like to avoid writing graphql queries. 

#### If this PR affects any API reference documentation, please share the updated endpoint references

It affects https://docs.authorizer.dev/authorizer-js/functions

### CODE REVIEW

**Comment by siimsams** [comment]
@lakhansamani Should i continue with this? Or were the admin queries left out on purpose?

**Comment by lakhansamani** [comment]
@siimsams what if we introduce new sdk for admin queries and mutations.

Reason to keep them is separate, is to avoid any hacks using sdks that is loaded on browser

**Comment by siimsams** [comment]
> @siimsams what if we introduce new sdk for admin queries and mutations.
> 
> Reason to keep them is separate, is to avoid any hacks using sdks that is loaded on browser

Sounds good. Can you create the repo? I can fill it out.

**Comment by lakhansamani** [comment]
@siimsams here is the new repo: https://github.com/authorizerdev/authorizer-js-admin

**Pull request closed without merging**
